apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
  labels:
    app: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: cicd
        image: localhost:8087/my-project:1.0
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: cicd-service
spec:
  selector:
    app: cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
